# 重命名此文件为 languages.toml 以启用多语言支持
[en]
languageName = "English"  # 英语的名称
languagedirection = "ltr"  # 语言方向为从左到右
title = "Example Site"  # 网站标题为 "示例站点"
weight = 1  # 权重设置为 1，影响语言选择的优先级

[zh]
languageName = "中文"  # 中文的名称
languagedirection = "ltr"  # 语言方向为从左到右
title = "Example Site"  # 网站标题为 "示例站点"
weight = 1  # 权重设置为 1，影响语言选择的优先级
