# 在部署之前修改 baseurl
baseurl = "https://chuidaofu.github.io/"  # 网站的基本 URL
languageCode = "en-us"  # 语言代码，设置为英语（美国）
title = "Chuidaofu"  # 网站标题

# 主题国际化支持
# 可用值：en（英语）、fr（法语）、id（印尼语）、ja（日本语）、ko（韩语），pt-br（巴西葡萄牙语）、zh-cn（简体中文）、zh-tw（繁体中文）、es（西班牙语）、de（德语）、nl（荷兰语）、it（意大利语）、th（泰语）、el（希腊语）、uk（乌克兰语）、ar（阿拉伯语）
defaultContentLanguage = "zn-ch"  # 默认内容语言设置为英语

# 如果默认内容语言为 [zh-cn ja ko] 中的任何一种，请将 hasCJKLanguage 设置为 true
# 这将使 .Summary 和 .WordCount 正确处理 CJK 语言
hasCJKLanguage = true  # 是否启用 CJK 语言支持，默认为 false

# 在使用之前，将其更改为您的 Disqus 短名称
disqusShortname = "hugo-theme-stack"  # Disqus 短名称，用于评论系统集成

[pagination]  # 分页设置
pagerSize = 3  # 每页显示的内容条目数量
